### ISSUE TITLE
Math not rendering in the website

### ISSUE THREAD

**Issue by joaovitorassumpcao** [UWCS/rs118#9]
Mdbook has the `mathjax-support = true` key, but it doesn't work with `$$` delimiters, so each one would need to be changed to `\\[ ... \\]`. 
So I made this issue just in case someone (myself included) would want to do this in the future.

**Comment by Joeyh021** [comment]
We use [mdbook-katex](https://github.com/lzanini/mdbook-katex) instead, as it pre-renders the equations instead of loading them at page load time like mathjax.

**Comment by joaovitorassumpcao** [comment]
Weird, no math is rendered in the site for me (rs118.uwcs.co.uk), and now on a second look TOC contents are now showing either.
[Proof](https://imgur.com/a/0VISsFq)


  
So I cloned the repo and made a minor change to `book.toml` as instructed in the katex repo:
```
[preprocessor.katex]
renderers = ["html"]

[output.katex]
```
and it is [working now](https://imgur.com/a/ILIrxuZ).

Is it rendering correctly for anyone else? I doubt it's an issue with my browser.
Should I make the commit to `Main` directly?
